apiVersion: v1
kind: Service
metadata:
  name: names
  namespace: kubernetes-education
  labels:
    app: names
spec:
  ports:
  - port: 8081
    name: http
  selector:
    app: names
---
apiVersion: v1
kind: Service
metadata:
  name: names-external
  namespace: kubernetes-education
spec:
  type: NodePort
  ports:
  - name: http
    port: 8766
    protocol: TCP
    targetPort: 8766
    # We dont usually set this
    nodePort: 31463
  selector:
    app: names